export const riddlesEnglish = [
  { riddle: "When you turn its head, it cries.", answer: "faucet" },
  { riddle: "Black crocodile.", answer: "asphalt" },
  { riddle: "It comes out of its mother's belly and beats its mother.", answer: "butter" },
  { riddle: "Door without a house.", answer: "mouth" },
  { riddle: "It has ears but can't hear.", answer: "corn" },
  { riddle: "It has legs but can't walk.", answer: "table" },
  { riddle: "It has teeth but doesn't bite.", answer: "comb" },
  { riddle: "It lives in the house, eaten in the field.", answer: "grain" },
  { riddle: "Tomorrow's man knows today's.", answer: "calendar" },
  { riddle: "It has one leg, travels everywhere.", answer: "umbrella" },
  { riddle: "What has keys but can't open doors?", answer: "piano" },
  { riddle: "What has a face but no eyes?", answer: "clock" },
  { riddle: "What has hands but cannot clap?", answer: "clock" },
  { riddle: "What has a neck but no head?", answer: "bottle" },
  { riddle: "What gets wetter as it dries?", answer: "towel" },
  { riddle: "What belongs to you but is used more by others?", answer: "name" },
  { riddle: "I’m tall when I’m young, and short when I’m old.", answer: "candle" },
  { riddle: "What has a head and a tail but no body?", answer: "coin" },
  { riddle: "I have branches but no fruit, trunk or leaves.", answer: "bank" },
  { riddle: "The more you take, the more you leave behind.", answer: "footsteps" },
  { riddle: "I’m always running but never move.", answer: "water" },
  { riddle: "The more you take from me, the bigger I get.", answer: "hole" },
  { riddle: "I’m full of holes but still hold water.", answer: "sponge" },
  { riddle: "What can travel around the world while staying in a corner?", answer: "stamp" },
  { riddle: "What has one eye but can’t see?", answer: "needle" },
  { riddle: "I’m light as a feather, yet the strongest man cannot hold me.", answer: "breath" },
  { riddle: "I’m always hungry and will die if not fed, but give me water and I’ll die.", answer: "fire" },
  { riddle: "I speak without a mouth and hear without ears.", answer: "echo" },
  { riddle: "The more you take me, the more you leave behind.", answer: "footsteps" },
  { riddle: "I have cities, but no houses; forests, but no trees; and water, but no fish.", answer: "map" },
  { riddle: "I can be cracked, made, told, and played.", answer: "joke" },
  { riddle: "I have keys that open no locks.", answer: "piano" },
  { riddle: "What runs but never walks?", answer: "river" },
  { riddle: "I’m invisible but you can see me when I reflect.", answer: "mirror" },
  { riddle: "I go up but never come down.", answer: "age" },
  { riddle: "I am not alive, but I grow.", answer: "fire" },
  { riddle: "I’m always in front of you but can’t be seen.", answer: "future" },
  { riddle: "I can be cracked, played, and told.", answer: "joke" },
  { riddle: "I’m easy to lift but hard to throw.", answer: "feather" },
  { riddle: "I have teeth but do not bite.", answer: "comb" },
  { riddle: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "letter M" },
  { riddle: "I can fly without wings.", answer: "time" },
  { riddle: "I can’t be touched but can be felt.", answer: "wind" },
  { riddle: "I get bigger the more you take away.", answer: "hole" },
  { riddle: "I have a bed but never sleep.", answer: "river" },
  { riddle: "I run but never walk.", answer: "water" },
  { riddle: "I’m tall when I’m young and short when I’m old.", answer: "candle" },
  { riddle: "I am always in the corner but can travel everywhere.", answer: "stamp" },
  { riddle: "I’m sometimes full, sometimes empty, and I hold water.", answer: "bucket" },
  { riddle: "I have hands but cannot clap.", answer: "clock" },
  { riddle: "I go up but never come down.", answer: "age" },
];

export const riddlesAmharic = [
  { riddle: "ጭንቅላቱን ሲያዞሩት የሚያለቅስ።", answer: "ቧንቧ" },
  { riddle: "ቲኩር አዞ።", answer: "አስፋልት" },
  { riddle: "ከእናቱ ሆድ ወጥታ እናቱን የምትመታ።", answer: "ቅቤ" },
  { riddle: "ቤት የሌለው ደጅ።", answer: "አፍ" },
  { riddle: "ጆሮ አለው ግን አይሰማም።", answer: "በቆሎ" },
  { riddle: "እግር አለው ግን አይራመድም።", answer: "ጠረጴዛ" },
  { riddle: "ጥርስ አለው ግን አይነክስም።", answer: "መንሸራተቻ" },
  { riddle: "በቤት ውስጥ የሚያድር በሜዳ የሚበላ።", answer: "እህል" },
  { riddle: "የነገ ሰው የዛሬውን ያውቃል።", answer: "የቀን መቁጠሪያ" },
  { riddle: "አንድ እግር አለው ሁሉን ቦታ ይጓዛል።", answer: "ጃንጥላ" },
  { riddle: "ቁልፎች አሉት ግን ቤት አይከፈትም።", answer: "ፒያኖ" },
  { riddle: "ፊት አለው ግን አይኖሩም።", answer: "ሰዓት" },
  { riddle: "እጆች አሉት ግን አይነጋገሩም።", answer: "ሰዓት" },
  { riddle: "አንድ አንገት አለው ግን ራሱ የለውም።", answer: "ጭማቂ" },
  { riddle: "ሲደምቅ እንደ ገና ደምቃል።", answer: "ሻሚያ" },
  { riddle: "ለእርስዎ ነው ግን ሌሎች ብዙ ይጠቀሙታል።", answer: "ስም" },
  { riddle: "ሲወለድ ረጅም ነኝ፣ ሲሞት አጭር ነኝ።", answer: "መብራት" },
  { riddle: "ራስና ጫማ አሉት ግን ሰው አይኖርም።", answer: "ብር" },
  { riddle: "ቅጥያዎች አሉት ግን ፍራንክ አይሰጥም።", answer: "ባንክ" },
  { riddle: "እርስዎ በሚወስዱት ጊዜ ተሞልቷ ይቀራል።", answer: "እግር ምልክት" },
  { riddle: "ሁልጊዜ ይሄዳል ግን አይንቀሳቀስም።", answer: "ውሃ" },
  { riddle: "ከእኔ የሚወስዱት ጊዜ ከፍ ይላል።", answer: "ቀንበር" },
  { riddle: "ብዙ ቦታዎች አሉት ግን ውሃን ይያዛል።", answer: "ስፖንጅ" },
  { riddle: "በዓለም ላይ ይጓዛል ግን በማዕከል ይቀመጣል።", answer: "ፖስታም" },
  { riddle: "አንድ አይ አለኝ ግን አልይም።", answer: "ሐኪም" },
  { riddle: "ቀውስ ነኝ ግን አልይም።", answer: "እስትም" },
  { riddle: "ምላስ አለኝ ግን አልሰማም።", answer: "ኤኮ" },
  { riddle: "እግሮችን ሲወስድ እየቀራ ይሄዳል።", answer: "እግር ምልክት" },
  { riddle: "ከእኔ ውስጥ ከተለዋዋጭ እንዲቀይር ይችላል።", answer: "ካርታ" },
  { riddle: "ሊታወቅ የሚችለውን እንደሚናገር እሰጣለሁ።", answer: "ጥሩ እንቆቅልሽ" },
  { riddle: "ቁልፎች አሉኝ ግን ቁልፎችን አልከፈትም።", answer: "ፒያኖ" },
  { riddle: "ምን ይሄዳል ግን አይንቀሳቀስም?", answer: "ወንዝ" },
  { riddle: "አራዊት አይደለም ግን ይጨምራል።", answer: "እሳት" },
  { riddle: "እንደ ወንዝ ይገኛል ግን ማንም አይሰማውም።", answer: "እረፍት" },
  { riddle: "ከእኔ የሚወስዱት ከፍ ይላል።", answer: "ቀንበር" },
  { riddle: "ከእኔ የሚቀይር የለም።", answer: "እሳት" },
  { riddle: "ሁልጊዜ ከአንድ በፊት ነኝ ግን አልታየም።", answer: "ወደፊት" },
  { riddle: "እቃ እንደ ገና ይሄዳል።", answer: "ጥሩ እንቆቅልሽ" },
  { riddle: "ከቀለም ቀለም የቀረው እንዴት ነው?", answer: "ጭነት" },
  { riddle: "አንድ ወንዝ አለኝ ግን አልወለድም።", answer: "ወንዝ" },
  { riddle: "ሁልጊዜ ይሄዳል ግን አይንቀሳቀስም።", answer: "ውሃ" },
  { riddle: "ሲወለድ ረጅም ነኝ ሲሞት አጭር ነኝ።", answer: "መብራት" },
  { riddle: "በክፍል ውስጥ ሁሉንም ይይዛል ግን በወገን አይነሳም።", answer: "ፖስታም" },
  { riddle: "ሲሞላ ሲባይ ውሃ ይይዛል።", answer: "ቅርጸ እቃ" },
  { riddle: "እጆች አሉት ግን አይነጋገሩም።", answer: "ሰዓት" },
  { riddle: "እርስዎ እንዴት ይጨምራሉ?", answer: "ዕድሜ" },
];
